---
kind: pipeline
type: exec
name: Build NixOS and home-manager

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - rm -rf $BUILDDIR/gcroots.tmp && mkdir -p $BUILDDIR/gcroots.tmp
  - nix shell nixpkgs#git nixpkgs#nix-build-uncached -c nix-build-uncached -build-flags "--out-link $BUILDDIR/gcroots.tmp/result" ./ci.nix
  - rm -rf $BUILDDIR/gcroots && mv $BUILDDIR/gcroots.tmp $BUILDDIR/gcroots
  environment:
    BUILDDIR: /var/lib/drone/doctor-build

- name: upload
  commands:
  - "\n      if stat -t $BUILDDIR/gcroots/result* >/dev/null 2>&1; then\n        nix path-info --json -r $BUILDDIR/gcroots/result* > $BUILDDIR/path-info.json\n        # only local built derivations\n        nix shell 'nixpkgs#jq' -c jq -r 'map(select(.ca == null and .signatures == null)) | map(.path) | .[]' < $BUILDDIR/path-info.json > paths\n        nix shell 'nixpkgs#cachix' -c cachix push --jobs 32 mic92 < paths\n      fi\n      "
  environment:
    BUILDDIR: /var/lib/drone/doctor-build
    CACHIX_SIGNING_KEY:
      from_secret: CACHIX_SIGNING_KEY
  when:
    event:
      exclude:
      - pull_request
    status:
    - failure
    - success

- name: send irc notification
  commands:
  - "LOGNAME=drone nix run .#irc-announce -- irc.r 6667 drone \"#xxx\" \"build $DRONE_SYSTEM_PROTO://$DRONE_SYSTEM_HOST/$DRONE_REPO/$DRONE_BUILD_NUMBER : $DRONE_BUILD_STATUS\" || true"
  environment:
    BUILDDIR: /var/lib/drone/doctor-build
  when:
    event:
      exclude:
      - pull_request
    status:
    - failure
    - success

trigger:
  event:
    exclude:
    - promote
    - rollback

---
kind: signature
hmac: b9765658fe29c56578fef602103efb5540da98fcae9524a111cd0efe17a8aac6

...
