---
kind: pipeline
type: exec
name: Build NixOS and home-manager

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - rm -rf $BUILDDIR/gcroots.tmp && mkdir -p $BUILDDIR/gcroots.tmp
  - nix shell nixpkgs#git nixpkgs#nix-build-uncached -c nix-build-uncached -build-flags "--out-link $BUILDDIR/gcroots.tmp/result" ./ci.nix
  - rm -rf $BUILDDIR/gcroots && mv $BUILDDIR/gcroots.tmp $BUILDDIR/gcroots
  environment:
    BUILDDIR: /var/lib/drone/doctor-build

- name: send irc notification
  commands:
  - "LOGNAME=drone nix run .#irc-announce -- irc.r 6667 drone \"#xxx\" \"build $DRONE_SYSTEM_PROTO://$DRONE_SYSTEM_HOST/$DRONE_REPO/$DRONE_BUILD_NUMBER : $DRONE_BUILD_STATUS\" || true"
  environment:
    BUILDDIR: /var/lib/drone/doctor-build
  when:
    event:
      exclude:
      - pull_request
    status:
    - failure
    - success

trigger:
  event:
    exclude:
    - promote
    - rollback

---
kind: signature
hmac: 33bef54c28fcfb6fbe35694039d2b0fd89540c83f1141a437d28671773fb0fa3

...
