stages:
  - build

build-job:
  stage: build
  script:
    - nix run nixpkgs/nixpkgs-unstable#nix-eval-jobs -- --workers $(nproc) --gc-roots-dir $(pwd)/gcroot --flake '.#hydraJobs' > jobs
    - nix run nixpkgs/nixpkgs-unstable#jq -- -r '.drvPath' < jobs | xargs -n1 -P$(nproc) nix build -L
    - |
      set -x
      if [[ -n "$CACHIX_AUTH_TOKEN" ]]; then
        realpath result* | nix run nixpkgs/nixpkgs-unstable#cachix -- push ${CACHIX_NAME:-tum-dse}
      fi
    - |
      if [[ -n "$GITHUB_TOKEN" ]]; then
        set -x
        meta=$(jq -cs '. | map({(.attr) : . })| add' < jobs)
        git -c "user.name=GitLab CI" -c "user.email=git@gitlab.com" tag -f "last-build" -m "last-build\n\n$meta"
        git push --force "https://Mic92:${GITHUB_TOKEN}@github.com/Mic92/${CI_PROJECT_NAME}.git" last-build
      else
        echo "no github token set"
      fi
  rules:
    - if: '$CI_COMMIT_REF_NAME != "last-build"'
  after_script:
    - |
       echo "build ${CI_JOB_URL}: $CI_JOB_STATUS" | \
         LOGNAME=gitlab nix run github:Mic92/nur-packages#ircsink -- --nick=gitlab --server=irc.r --target="#xxx"
