pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - check-success=ci/hydra:dotfiles:flake-update:nixos-amy
      - check-success=ci/hydra:dotfiles:flake-update:nixos-bill
      - check-success=ci/hydra:dotfiles:flake-update:nixos-clara
      - check-success=ci/hydra:dotfiles:flake-update:nixos-doctor
      - check-success=ci/hydra:dotfiles:flake-update:nixos-donna
      - check-success=ci/hydra:dotfiles:flake-update:nixos-graham
      - check-success=ci/hydra:dotfiles:flake-update:nixos-martha
      - check-success=ci/hydra:dotfiles:flake-update:nixos-nardole
      - check-success=ci/hydra:dotfiles:flake-update:nixos-rose
      - check-success=ci/hydra:dotfiles:flake-update:nixos-ryan
      - check-success=ci/hydra:dotfiles:flake-update:nixos-sauron
      - check-success=ci/hydra:dotfiles:flake-update:nixos-yasmin
      - author=github-actions[bot]
    actions:
      merge:
        method: merge
      delete_head_branch: {}
