keys:
  - &joerg age17n64ahe3wesh8l8lj0zylf4nljdmqn28hvqns2g7hgm9mdkhlsvsjuvkxz
  - &peter age1r8v7gf5wxmggsecapn2ptm3q6gjpyquw2fm3dwhr59jpmyjvzcfqd03zcd
  - &cmainas age1et533lu2xqnxl5k332f2q57hqxu8j7j4lrzcannqynfmf9xh2azqfzheu4
  - &amy age137rtvc63e3rg0qtlc8nwmajqljuckjdptncd4nmk8w8hvdlcr3tsj2f8d8
  - &clara age1hsvqmpun5c4ht8vk9pjhppav3zdxm37h820uws07xe88gpejfs6qyzhwav
  - &rose age18s9fs98d44dcgn2cn9a4p3zryc0z88u2wmrs62yvyr06gzxpzdnshp70vp
  - &donna age1tmauqc99j526s4gpjxz335jag423utcjpldak6ealu6c796n59xqq62wja
  - &martha age12fzpr4rm4xwm9t8jwyeu449lsetxruv9mf9m28jqwkvs86yrlqnqn8kfcd
  - &doctor age1t7mujjjvczz9gsrsalegr79yp424scpx0mcxl6c3j7stmea8falqqnu9p7
  - &bill age1mfwpvl4fkjukpjc3502dgalvmllg5mzl8xq0p6wz2xegeev8r5ksjc2flq
  - &nardole age17ye252kv8u3qp0lkgknyl3jlaj8c0z92z65evaj8ss7q6axcud9s8prv32
  - &sauron age1t447x7xtqqhmfr026uhfn6ys62hlhseakw9qlrveadqxk7sehyysx62rq9
  - &yasmin age1ygw55360m3gjquperauv50u6zd6rkl2uuergycl6apf92ycc8gkqktdcm6
  - &graham age1qnz850jesp6l4968vqdp40mqenmtx3czhy5l8hsz4kym3aj8c56srs5dkk
  - &ryan age1cxtzg79g4ueqawa2hwstkkyeyq6e53q6r4te527lnjvzhujjc5ns96qehp
  - &astrid age1hen4wskutter8h4ypkhv7aqvh7mr9gl7pz7gd9mgln4jl2ckxq7qaks7h6
  - &mickey age120dyz5upjmv0z4e23vj2dhcm0c5cvm6tmwzl5sj5ye4jrjtwg4tsy3n7m3
  - &dan age1l86ru9amzp3g484wevpa64yjn8ppw0wn2qhud8xz05q84hvq0p0qatqpvq
  - &christina age168tqvf7373e7wj0q8p0trzm5t0mvlp4t296uuswa98s2waerfsgqdvzmhe
admins: &admins
  - *joerg
  - *peter
  - *cmainas
# command to add a new age key for a new host
# nix-shell -p ssh-to-age --run "ssh-keyscan $host | ssh-to-age"
creation_rules:
  - path_regex: modules/sshd/[^/]+\.yaml$
    key_groups:
    - age: *admins
  - path_regex: hosts/amy.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *amy
  - path_regex: hosts/clara.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *clara
  - path_regex: hosts/rose.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *rose
  - path_regex: hosts/donna.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *donna
  - path_regex: hosts/martha.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *martha
  - path_regex: hosts/doctor.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *doctor
  - path_regex: hosts/bill.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *bill
  - path_regex: hosts/nardole.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *nardole
  - path_regex: hosts/sauron.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *sauron
  - path_regex: hosts/yasmin.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *yasmin
  - path_regex: hosts/graham.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *graham
  - path_regex: hosts/ryan.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *ryan
  - path_regex: hosts/astrid.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *astrid
  - path_regex: hosts/mickey.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *mickey
  - path_regex: hosts/dan.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *dan
  - path_regex: hosts/christina.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *christina
  - path_regex: modules/nfs/secrets.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *bill
      - *nardole
  - path_regex: modules/k3s/secrets.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *bill
      - *nardole
      - *astrid
      - *mickey
      - *dan
  - path_regex: modules/gitlab-runner/secrets.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *ryan
  - path_regex: modules/secrets.yml$
    key_groups:
    - age:
      - *joerg
      - *peter
      - *cmainas
      - *amy
      - *astrid
      - *clara
      - *rose
      - *dan
      - *donna
      - *martha
      - *mickey
      - *doctor
      - *bill
      - *nardole
      - *sauron
      - *graham
      - *ryan
      - *yasmin
  - path_regex: secrets.yml$
    key_groups:
    - age: *admins
  - path_regex: terraform/secrets.enc.json$
    key_groups:
    - age: *admins
