---
- name: Setup sftp-only access to deploy sshd keys from nix
  hosts: all
  become: yes
  tasks:
   - name: Add user to deploy ssh keys via sftp
     user:
      name: deploy
      state: present
      shell: /bin/sh
      home: /
      system: yes
      createhome: no
   - name: Allow deploy user to update tunnel keys
     community.general.sudoers:
       name: update-tunnel-keys
       user: deploy
       commands: /usr/local/bin/update-tunnel-keys
   - name: Add command to deploy tunnel keys
     copy:
       dest: /usr/local/bin/update-tunnel-keys
       owner: root
       group: root
       mode: '0755'
       content: |
         #!/usr/bin/env bash
         echo "Updating ssh keys..."
         /bin/cat > /etc/ssh/authorized_keys.d/tunnel
   - name: Add user for ssh forwarding
     user:
      name: tunnel
      state: present
      shell: /usr/sbin/nologin
      system: yes
      createhome: yes
      home: /var/lib/tunnel
   - name: Append to sshd_config
     blockinfile:
       block: "{{ lookup('file', './sshd_config') }}"
       path: /etc/ssh/sshd_config
     register: sshd_conf
   - name: add SSH ca cert
     copy:
       dest: /etc/ssh/login-cert.pub
       owner: root
       group: root
       mode: '0644'
       content: |
         {{ lookup('file', './../sshd/certs/login-cert.pub') }}
     register: ssh_cert
   - name: reload sshd
     service:
       name: ssh
       state: reloaded
     when: sshd_conf.changed or ssh_cert.changed
   - name: Create /etc/ssh/authorized_keys.d
     file:
       path: /etc/ssh/authorized_keys.d
       owner: root
       group: root
       mode: '0755'
       state: directory
   - name: Create empty ssh key file for tunnel user
     file:
       path: /etc/ssh/authorized_keys.d/tunnel
       owner: root
       group: root
       mode: '0644'
       state: touch
   - name: Add ssh key for deploy user
     copy:
       dest: /etc/ssh/authorized_keys.d/deploy
       owner: root
       group: root
       mode: '0644'
       content: |
         ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINpkqkEz8grxBHfDecJwTHi14lcaZOgUA5HbKP/2tdia

   - name: Update and upgrade apt packages for security updates
     apt:
       upgrade: yes
       update_cache: yes
       autoclean: yes
       autoremove: yes
       cache_valid_time: 86400 #One day
     register: system_upgrade
   - name: Reboot the machine when updates have been applied
     reboot:
     when: system_upgrade.changed
