---
- name: Setup sftp-only access to deploy sshd keys from nix
  hosts: all
  become: yes
  tasks:
   - name: Add user to deploy ssh keys via sftp
     user:
      name: deploy
      state: present
      shell: /usr/sbin/nologin
      system: yes
      createhome: no
   - name: Add user for ssh forwarding
     user:
      name: tunnel
      state: present
      shell: /usr/sbin/nologin
      system: yes
      createhome: yes
      home: /var/lib/tunnel
   - name: Append to sshd_config
     blockinfile:
       block: "{{ lookup('file', './sshd_config') }}"
       path: /etc/ssh/sshd_config
     register: sshd_conf
   - name: add SSH ca cert
     copy:
       dest: /etc/ssh/login-cert.pub
       owner: root
       group: root
       mode: '0644'
       content: |
         {{ lookup('file', './../sshd/certs/login-cert.pub') }}
     register: ssh_cert
   - name: reload sshd
     service:
       name: ssh
       state: reloaded
     when: sshd_conf.changed or ssh_cert.changed
   - name: Create /etc/ssh/authorized_keys.d
     file:
       path: /etc/ssh/authorized_keys.d
       mode: '0755'
       state: directory
   - name: allow deploy user to change the tunnel user config
     ansible.posix.acl:
       path: /etc/ssh/authorized_keys.d/tunnel
       entity: deploy
       etype: user
       permissions: rw
       state: present
   - name: Create empty ssh key file for tunnel user
     file:
       path: /etc/ssh/authorized_keys.d/tunnel
       owner: root
       group: root
       mode: '0644'
       state: touch
   - name: Add ssh key for deploy user
     copy:
       dest: /etc/ssh/authorized_keys.d/deploy
       owner: root
       group: root
       mode: '0644'
       content: |
         ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINpkqkEz8grxBHfDecJwTHi14lcaZOgUA5HbKP/2tdia

   - name: Update and upgrade apt packages for security updates
     apt:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400 #One day
