---
- name: Upgrade and reboot monitoring Ubuntu VM that runs our monitoring
  hosts: all
  become: yes
  tasks:
   - name: Update and upgrade apt packages for security updates
     apt:
       upgrade: yes
       update_cache: yes
       autoclean: yes
       autoremove: yes
       cache_valid_time: 86400 # One day
     register: system_upgrade
   - name: Reboot the machine when updates have been applied
     reboot:
     when: system_upgrade.changed
